consensys-vertical-apps/metamask-institutional

- .npmrc
> chore(npmrc): clean up

- .github/workflows/npm-publish.yml
- .github/workflows/tests.yml
- .npmrc
> chore(token): NODE_AUTH_TOKEN

- .npmrc
> chore(npmrc): removes npmrc

- packages/mmiController/.gitignore
- packages/mmiController/.npmignore
- packages/mmiController/CHANGELOG.md
- packages/mmiController/LICENSE.md
- packages/mmiController/README.md
- packages/mmiController/jest.config.js
- packages/mmiController/package.json
- packages/mmiController/src/MMIController.ts
- packages/mmiController/src/index.ts
- packages/mmiController/src/transaction.ts
- packages/mmiController/src/types.ts
- packages/mmiController/tsconfig.json
- packages/types/src/types/MetamaskTransaction.ts
- yarn.lock
Adds the mmi-controller to the monorepo.
> MMI adds mmi controller to the monorepo

- packages/custodyKeyring/package.json
> fix(version bump): version increase

- .release-please-manifest.json
- packages/mmiController/package.json
- release-please-config.json
Adds packages/mmiController to the release-please json config files
> fix(updates release-please): updates release-please

- .release-please-manifest.json
- packages/extension/package.json
Extension package, manual version bump.
> chore(version): version

- packages/extension/src/ExtensionUtils.test.ts
- packages/extension/src/ExtensionUtils.ts
Updates methods names to:
- setDeferredSignSuccess
- setDeferredSignError
> chore(extensionutils): signatureController methods names

- packages/custodyKeyring/package.json
> fix(custodykeyring): bumps version

- packages/mmiController/package.json
- yarn.lock
Reverts consensys-vertical-apps/metamask-institutional#404
> Revert "chore(deps): bump @metamask/eth-keyring-controller from 10.0.1 to 13.0.0"

- packages/sdk/src/custodianApi/bitgo/BitgoClient.ts
- packages/sdk/src/custodianApi/cactus/CactusClient.ts
- packages/sdk/src/custodianApi/qredo/QredoClient.ts
Throws error if Fetch request fails for Qredo, Cactus and Bitgo clients.
> fix(fetchapi): error throw with fetch api

- packages/configurationClient/src/ConfigurationClient.ts
- packages/custodyKeyring/src/MmiConfiguration.ts
- packages/custodyKeyring/src/custodianTypes/curv/CurvCustodyKeyring.ts
- packages/sdk/src/custodianApi/eca3/rpc-payloads/JsonRpcReplaceTransactionPayload.ts
> fix(lint): lint issues were fixes

- packages/sdk/src/custodianApi/eca3/ECA3CustodianApi.ts
Cleans old testing eca3 methods.
> chore(cleanup): cleanup

- package.json
- packages/extension/src/ExtensionUtils.ts
Don't set submitted status AFTER confirmation
> fix: dont set submitted after confirmation

- packages/sdk/src/custodianApi/eca3/ECA3Client.ts
- packages/sdk/src/custodianApi/json-rpc/JsonRpcClient.test.ts
- packages/sdk/src/custodianApi/json-rpc/JsonRpcClient.ts
Jira ticket
https://consensyssoftware.atlassian.net/jira/software/projects/MMI/boards/315/backlog?assignee=5cfa627c9943230e77ad45eb&selectedIssue=MMI-4497
> fix: only create an ITR event if the custodian returns a URL where the user can go

- .github/workflows/tests.yml
- jest.config.js
- package.json
- Add cache in unit tests (should improve UT performance time)
- Adds UT report in summary
- Adds tsc type-check
Update codeowners with github/** @consensys-vertical-apps/directu-mmi-techlead
This PR does not require tests. Is a infra PR
> ci: add tsc command and jest cache

- packages/extension/package.json
- packages/extension/src/ExtensionUtils.ts
We cant use/mutate the original txMeta anymore since from now on  it's immutable.
> fix(extensionUtils): we have to clonedeep txmeta

- packages/extension/src/ExtensionUtils.ts
Adds missing logic to take care of the hash (updating it in our local object) and also updates the txMeta object in the transaction-controller.
> fix(txstatus): adds missing logic to take care of the hash

- packages/rpcAllowlist/src/rpc-allowed-origins.ts
Revemos the codefi regex and fixes the metamask-institutional.io regex.
Ticket reference: https://consensyssoftware.atlassian.net/browse/MMI-4835
> Mmi 4835 clean up and fix rpc allowed origins regexes

- packages/rpcAllowlist/src/rpc-allowed-origins.ts
> fix(lint): lint and prettier fix

- .github/workflows/generate-changelog.yml
- packages/rpcAllowlist/CHANGELOG.md
- packages/rpcAllowlist/package.json
Manual publish and adds "refactor" trigger to gh action.
> refactor(manual publish): adds refactor trigger

- packages/sdk/src/custodianApi/eca3/ECA3Client.ts
- packages/sdk/src/custodianApi/json-rpc/JsonRpcClient.ts
- Handles json response correctly
> fix(refresh-token): logic around refresh token

- packages/custodyKeyring/src/CustodyKeyring.ts
- packages/custodyKeyring/src/interfaces/ICustodyKeyringOptions.ts
Adds error handling and sentry `captureException` for the `deserialize` method.
> chore(error log): adds try catch and sentry log with captureException

- packages/custodyKeyring/package.json
custody-keyring version manual update
> fix(manual update): manual update

- packages/rpcAllowlist/src/rpc-allowed-origins.test.ts
- packages/rpcAllowlist/src/rpc-allowed-origins.ts
Allows for hostname to be exactly MMI_HOSTNAME without any subdomain.
> fix(rpc-allowed-origins): allow for root mmi url

- packages/custodyKeyring/src/MmiConfiguration.test.ts
- packages/custodyKeyring/src/MmiConfiguration.ts
- packages/custodyKeyring/src/interfaces/ICustodianEnvironment.ts
- packages/custodyKeyring/src/interfaces/IJsonRpcCustodian.ts
- packages/institutionalFeatures/src/institutional-features.test.ts
- packages/institutionalFeatures/src/institutional-features.ts
- packages/transactionUpdate/src/TransactionUpdate.test.ts
- packages/transactionUpdate/src/TransactionUpdate.ts
- packages/types/src/index.ts
- packages/types/src/types/ConnectRequest.ts
- packages/types/src/types/ConnectionRequest.ts
- packages/websocketClient/src/WebsocketClient.test.ts
- packages/websocketClient/src/WebsocketClient.ts
- packages/websocketClient/src/interfaces/IWebsocketClientControllerOptions.ts
> feat(websocketclient transasctionupdate): initial handshake work

- CODEOWNERS
Adds CODEOWNERS file with specific rules for important packages and team responsible.
Prior to this PR the repo has been set to require a minimum of 2 reviewers in a PR.
> chore(codeowners): adds codeowners file

- packages/sdk/package.json
> fix(sdk): bump version

- packages/custodyKeyring/src/CustodyKeyring.ts
- packages/custodyKeyring/src/custodianTypes/qredo/QredoCustodyKeyring.ts
> chore: always return qredo as env in qredo keyring

- .release-please-manifest.json
- packages/custodyController/package.json
- packages/custodyKeyring/package.json
- packages/extension/package.json
- packages/institutionalFeatures/package.json
- packages/transactionUpdate/package.json
- packages/websocketClient/package.json
Manual bump custody-keyring version.
> chore(bump version): bump version

- packages/custodyKeyring/src/CustodyKeyring.ts
Small improvement for future cases.
> fix(supportedchainids): better error handling

- packages/sdk/package.json
> fix(sdk): manual publish sdk

- packages/sdk/package.json
> fix(sdk): manual publish sdk part 2

- .release-please-manifest.json
- packages/custodyController/package.json
- packages/custodyKeyring/src/CustodyKeyring.ts
- packages/sdk/src/classes/MMISDK.ts
- packages/sdk/src/custodianApi/json-rpc/JsonRpcCustodianApi.ts
> fix(version bump): manual version bump and clean up

- .gitignore
- packages/custodyKeyring/src/index.ts
Remove the export of the Migrator class from CustodyKeyring index
> perf(custody-keyring): remove migrations from index

- .github/workflows/npm-publish.yml
- package.json
Our current CI/CD pipeline is failing due to a version incompatibility between our specified Node.js version and the requirements of the Lerna package. Specifically, Lerna requires Node.js version 18.0.0 or higher, but our workflow is currently using Node.js 16.20.2.
This pull request updates our GitHub Actions workflow and package.json to use Node.js version 18, ensuring compatibility with the latest version of Lerna.
> fix: fix npm publish node version

- packages/custodyKeyring/package.json
> chore(custody-keyring): bump version to trigger release
